### ISSUE TITLE
How to get the plugin work

### ISSUE THREAD

**Issue by golodhrim** [Ovyerus/obsidian-klog#1]
I tried to download your v0.2.0 release version and copied it to the desired obsidian installation, but it fails to load, also after trying to activate it fails and building from source is not working under MacOS. Sadly there is no information of how to get it work. Could you either try to provide a final version that one could use, or tell what one needs to do to get it working.

**Comment by Ovyerus** [comment]
Sorry about that, don't know how I forgot to attach the compiled plugin to the release. The files have been uploaded.
